// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyUrZclhWRQjb0OLqFwa7V01rs-WF2FbI',
    appId: '1:884537469871:web:d90a6d89f7cb2fb4a69d5a',
    messagingSenderId: '884537469871',
    projectId: 'football-booking-41e1b',
    authDomain: 'football-booking-41e1b.firebaseapp.com',
    storageBucket: 'football-booking-41e1b.firebasestorage.app',
    measurementId: 'G-GJ1SWWFKS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpeTD0h_BSqWCzjgtMQboh6yCMeHjvyE',
    appId: '1:884537469871:android:71c1c38bd6398cb9a69d5a',
    messagingSenderId: '884537469871',
    projectId: 'football-booking-41e1b',
    storageBucket: 'football-booking-41e1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlpeTD0h_BSqWCzjgtMQboh6yCMeHjvyE',
    appId: '1:884537469871:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '884537469871',
    projectId: 'football-booking-41e1b',
    storageBucket: 'football-booking-41e1b.firebasestorage.app',
    iosBundleId: 'com.example.football',
  );
}
